### ISSUE TITLE
Passing in `SubParams` to `SubmitTransaction`

### ISSUE THREAD

**Issue by sgerbino** [koinos/koinos-util-golang#23]
The code suggests that `SubParams` can be `nil`, yet it dereferences the object first thing. The code should either accept `nil` and not dereference or the `nil` check in the conditional is unnecessary.

https://github.com/koinos/koinos-util-golang/blob/4faf8205b8eddff83ee3cc0817ea6987e7576f86/rpc/koinos_rpc_client.go#L176-L190

**Comment by mvandeberg** [comment]
Closes by #24
